version: "3"
services:
  test:
    build: .
    ports:
      - "3078"
    container_name: nexgddp-test
    environment:
      PORT: 3078
      DEBUG: "True"
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4MjBhZDk0NjlhMDI4Nzk4MmY0Y2QxOCIsInByb3ZpZGVyIjoibG9jYWwiLCJwcm92aWRlcklkIjpudWxsLCJlbWFpbCI6InNlcmdpby5nb3JkaWxsb0B2aXp6dWFsaXR5LmNvbSIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRBdCI6IjIwMTYtMTEtMDdUMTY6MzY6MzYuODY4WiIsImV4dHJhVXNlckRhdGEiOnsiYXBwcyI6WyJnZnciLCJwcmVwIiwiYXF1ZWR1Y3QiLCJmb3Jlc3QtYXRsYXMiLCJydyIsImRhdGE0c2RnIl19fQ.3GzuhG8wD4gI5Fo6NTqHC_Dq6ChKPPWXygga2mAuKZw
      GATEWAY_URL: http://mymachine:9000
      RASDAMAN_URL: http://rasdaman:9876/
      REDIS_URL: redis://redis:6379
      GOOGLE_APPLICATION_CREDENTIALS: /opt/nexgddp/storage.json
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      GCLOUD_STORAGE: "$GCLOUD_STORAGE"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "True"
    command: test
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
